// Generated by CoffeeScript 1.8.0
var ball, draw, init, rect;

init = function() {
  var canvas, context, gameField, simpleBall;
  document.getElementById("btn").onclick = function() {
    return alert("click!");
  };
  canvas = document.getElementById("ballpool");
  canvas.width = 800;
  canvas.height = 600;
  context = canvas.getContext("2d");
  simpleBall = ball(context, "#F00", 0, 0, 10);
  return gameField = rect(context, "#555", 0, 0, 800, 600);
};

draw = function() {
  simpleBall.draw();
  return gameField.draw();
};

rect = function(context, color, x, y, width, height) {
  this.context = context;
  this.color = color;
  this.x = x;
  this.y = y;
  this.width = width;
  this.height = height;
  this.draw = function() {
    this.context.fillStyle = this.color;
    return this.context.fillRect(this.x, this.y, this.width, this.height);
  };
  return this;
};

ball = function(context, color, x, y, radius) {
  this.context = context;
  this.color = color;
  this.x = x;
  this.y = y;
  this.radius = radius;
  return this.draw = function() {
    this.context.beginPath();
    this.context.fillStyle = "#0000ff";
    this.context.arc(x, y, radius, 0, Math.PI * 2, true);
    this.context.closePath();
    return this.context.fill();
  };
};
