// Generated by CoffeeScript 1.8.0
var init, rect;

init = function() {
  var canvas, context, gameField;
  document.getElementById("btn").onclick = function() {
    return alert("click!");
  };
  canvas = document.getElementById("ballpool");
  canvas.width = 800;
  canvas.height = 600;
  context = canvas.getContext("2d");
  gameField = rect(context, "#555", 0, 0, 800, 600);
  return gameField.draw();
};

rect = function(context, color, x, y, width, height) {
  this.context = context;
  this.color = color;
  this.x = x;
  this.y = y;
  this.width = width;
  this.height = height;
  this.draw = function() {
    this.context.fillStyle = this.color;
    return this.context.fillRect(this.x, this.y, this.width, this.height);
  };
  return this;
};
