// Generated by CoffeeScript 1.8.0
(function() {
  var init, rect;

  init = function() {
    var canvas, context, gameField;
    gameField = new rect("#555", 0, 0, 800, 600);
    canvas = document.getElementById("ballpool");
    canvas.width = gameField.width;
    canvas.height = gameField.height;
    context = canvas.getContext("2d");
    return gameField.draw();
  };

  rect = function(color, x, y, width, height) {
    this.color = color;
    this.x = x;
    this.y = y;
    this.width = width;
    this.height = height;
    return this.draw = function() {
      context.fillStyle = this.color;
      return context.fillRect(this.x, this.y, this.width, this.height);
    };
  };

  document.getElementById("btn").onclick = function() {
    return alert("click!");
  };

  init();

}).call(this);
